version: '3.9'
services:
  app:
    build: .
    image: maayanlab/rummagene
    environment:
      - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB
      - AUTHORIZATION_HEADER=$AUTHORIZATION_HEADER
      - NODE_ENV=production
    ports:
      - 3000:3000
  postgres:
    build: db
    image: maayanlab/rummagene-postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
