version: '3.9'
services:
  graphql:
    build: graphql
    image: maayanlab/sigcom-lite-graphql
    command:
    - --connection
    - postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB
    - --schema
    - app_public
    - --watch
    - --enhance-graphiql
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
  postgres:
    build: postgres
    image: maayanlab/sigcom-lite-postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
