version: '3.9'
services:
  l2s2-app:
    build: .
    platform: linux/amd64
    image: maayanlab/l2s2:0.0.9
    x-kubernetes:
      imagePullPolicy: IfNotPresent
      annotations:
        maayanlab.cloud/ingress: https://l2s2.maayanlab.cloud
    environment:
      - PUBLIC_URL=https://l2s2.maayanlab.cloud
      - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@l2s2-postgres/$POSTGRES_DB
      - AUTHORIZATION_HEADER=$AUTHORIZATION_HEADER
      - NODE_ENV=production
      - ENRICH_URL=http://l2s2-enrich:8000
      - NEXT_PUBLIC_GA_MEASUREMENT_ID=$NEXT_PUBLIC_GA_MEASUREMENT_ID
    ports:
      - 3000:3000
  l2s2-enrich:
    build: enrich
    platform: linux/amd64
    image: maayanlab/l2s2-enrich:0.1.0
    deploy:
      resources:
        reservations:
          memory: 5Gb
    environment:
      - 'ROCKET_DATABASES={postgres={url="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@l2s2-postgres/${POSTGRES_DB}"}}'
    ports:
      - 8000:8000
  l2s2-postgres:
    build: db
    platform: linux/amd64
    image: maayanlab/l2s2-postgres:0.0.1
    shm_size: 1Gb
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - ENRICH_URL=http://l2s2-enrich:8000
    ports:
      - 5432:5432
    volumes:
      - l2s2-data-2:/var/lib/postgresql/data

volumes:
  l2s2-data-2:
    x-kubernetes:
      size: 50Gi
      class: gp2

x-kubernetes:
  name: l2s2
  namespace: l2s2