version: '3.9'
services:
  graphql:
    build: graphql
    image: maayanlab/sigcom-lite-graphql
    environment:
      - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB
      - AUTHORIZATION_HEADER=$AUTHORIZATION_HEADER
      - NODE_ENV=development
    ports:
      - 5000:5000
  postgres:
    build: db
    image: maayanlab/sigcom-lite-postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
