version: '3.9'
services:
  rummagene-app:
    build: .
    image: maayanlab/rummagene:0.3.2
    environment:
      - PUBLIC_URL=https://rummagene.com
      - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@rummagene-postgres/$POSTGRES_DB
      - AUTHORIZATION_HEADER=$AUTHORIZATION_HEADER
      - NODE_ENV=production
      - ENRICH_URL=http://rummagene-enrich:8000
      - NEXT_PUBLIC_GA_MEASUREMENT_ID=$NEXT_PUBLIC_GA_MEASUREMENT_ID
    ports:
      - 3000:3000
    volumes:
      - ./data/bot/output-clean.gmt:/app/public/latest.gmt:ro
  rummagene-enrich:
    build: enrich
    image: maayanlab/rummagene-enrich:0.2.2
    environment:
      - 'ROCKET_DATABASES={postgres={url="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@rummagene-postgres/${POSTGRES_DB}"}}'
    ports:
      - 8000:8000
  rummagene-postgres:
    build: db
    image: maayanlab/rummagene-postgres:0.1.3
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - ENRICH_URL=http://rummagene-enrich:8000
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
  rummagene-bot:
    build: bot
    image: maayanlab/rummagene-bot:0.2.1
    command: ["bash", "-c", "cd /work/data && touch log && tail -f log"]
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@rummagene-postgres:5432/${POSTGRES_DB}
      - ENRICH_URL=http://rummagene-enrich:8000
      - API_KEY
      - EMAIL
    volumes:
      - ./data/bot/:/work/data
    labels:
      ofelia.enabled: "true"
      # 0 second
      # 0 minute
      # 9 hour
      # * day of month
      # * month of year
      # 1 day of week (monday)
      ofelia.job-exec.update-db.schedule: "0 0 9 * * 1"
      ofelia.job-exec.update-db.command: "/bin/sh -c '/work/bot.sh > /work/data/log 2> /work/data/log'"
  cron:
    image: mcuadros/ofelia:latest
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
