import Image from 'next/image'
import React from 'react'
import Stats from '@/components/stats'

export default function HomeLayout({ children }: React.PropsWithChildren<{}>) {
  return (
    <div className="flex justify-center">
      <div className="flex flex-col lg:flex-row items-center justify-center">
        <div className="card max-w-xs shadow-2xl bg-base-100 flex-shrink-0">
          <div className="card-body">
            {children}
          </div>
        </div>
        <div className="text-center p-10">
          <h3 className="text-xl font-bold p-2 pt-0">
            LINCS L1000 Signatures Search
          </h3>
          <div className='inline-flex'>
            <Image className={'rounded'} src={'/images/LINCSearch_logo.png'} width={225} height={225} alt={'Rummagene'}></Image>
          </div>
          <React.Suspense fallback={<div className="text-center p-5"><Image className={'rounded mx-auto'} src={'/images/loading.gif'} width={125} height={250} alt={'Loading...'}/> </div>}>
          <h1 className="text-2xl font-bold">
            <span className="whitespace-nowrap"> Search through <Stats bold show_gene_sets /></span>
          </h1>
          <div>
            <span className="whitespace-nowrap"> generated by the Library of Integrated Network-based Cellular Signatures</span>
            <p> (LINCS) program to find the most similar gene sets that match your query.</p>
          </div>
          <div className="mt-5">
            <span className="whitespace-nowrap">L2S2 includes over 1.4 million chemical perturbation and over 280,000 CRISPR knockout signatures.</span>
          </div>
          <div className="mt-5">
          <p className='mb-2 font-bold'>Please acknowledge L2S2 in your publications by citing the following reference: </p>
          </div>
          <div className='text-left pl-24'>
          <p className=''>Giacomo B Marino, John E Evangelista, Daniel J B Clarke, Avi Ma&apos;ayan, </p>
          <p> L2S2: chemical perturbation and CRISPR KO LINCS L1000 signature search engine. </p><p><i>Nucleic Acids Res</i>, 2025; gkaf373, <a className="underline text-blue-600 cursor-pointer" href='https://doi.org/10.1093/nar/gkaf373' target='_blank'>https://doi.org/10.1093/nar/gkaf373</a></p>
          </div>

          </React.Suspense>
        </div>
      </div>
    </div>
  )
}